/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ehu.isad;

import javafx.application.Application;
import javafx.stage.Stage;

public class Main extends Application {

    private Stage stage;

    public static void main(String[] args) {
        launch();
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        stage = primaryStage;
        stage.setResizable(false);
        stage.show();
        stage.setTitle("Eurobisioa");
    }
}
